# Let's define a default value for all 15 levels of Attribute Precedence
# as described in https://docs.chef.io/attributes.html
default[:precedence][:lvl_1] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_2] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_3] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_4] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_5] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_6] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_7] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_8] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_9] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_10] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_11] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_12] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_13] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_14] = "Precedence: default - Coobook: attribute_default - Attribute File"
default[:precedence][:lvl_15] = "Precedence: default - Coobook: attribute_default - Attribute File"
