# Normal
normal[:precedence][:lvl_7] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_8] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_9] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_10] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_11] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_12] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_13] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_14] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
normal[:precedence][:lvl_15] = "Precedence: normal - Coobook: attribute_normal - Attribute File"
