node.override[:precedence][:lvl_10] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
node.override[:precedence][:lvl_11] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
node.override[:precedence][:lvl_12] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
node.override[:precedence][:lvl_13] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
node.override[:precedence][:lvl_14] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
node.override[:precedence][:lvl_15] = "Precedence: override - Coobook: attribute_override - Recipe: set_attributes.rb"
